import { Inter } from "next/font/google";
import "../globals.css";
import SecondaryNavbar from "@/common/navbar/SecondaryNavbar";
import Footer from "@/common/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "RAZE",
    description: "Generated by create next app",
};


export default function LoginLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <SecondaryNavbar />
                <main className="mt-28">
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
