import Footer from "@/common/footer/Footer";
import SecondaryNavbar from "@/common/navbar/SecondaryNavbar";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "RAZE",
    description: "Generated by create next app",
};


export default function LoginLayout({ children, session }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <SecondaryNavbar />
                <SessionProvider session={session}>
                    <main className="mt-28">
                        {children}
                    </main>
                </SessionProvider>
                <Footer />
            </body>
        </html>
    );
}
