import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/common/navbar/Navbar";
import Footer from "@/common/footer/Footer";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RAZE",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Navbar />
          <main>
            {children}
          </main>
        </SessionProvider>
        <Footer />
      </body>
    </html>
  );
}
